# fly.toml app configuration file generated for app-snowy-grass-6764 on 2024-10-15T00:30:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-snowy-grass-6764'
primary_region = 'iad'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
